'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

module.exports = async function run() {
  const html = fs.readFileSync(path.join(process.cwd(), 'public/dashboard.html'), 'utf8');

  assert.ok(html.indexOf('id="globalRainIndicator"') > -1, 'global rain indicator missing');
  assert.strictEqual(html.indexOf('class="card-head"'), -1, 'legacy card header rows should be removed');
  assert.ok(html.indexOf('class="panel-corner-icon"') > -1, 'corner icon primitive missing');
  assert.ok(html.indexOf('class="card-icon"') > -1, 'card icon element missing');
  assert.ok(html.indexOf('id="mainRadar"') > -1, 'main radar panel missing');
  assert.ok(html.indexOf('id="mainSolar"') > -1, 'main solar panel missing');
  assert.ok(html.indexOf('id="customCard"') > -1, 'custom card placeholder missing');
  assert.ok(html.indexOf('id="takeoverBlackout"') > -1, 'takeover blackout layer missing');
  assert.ok(html.indexOf('id="topDateBadge"') > -1, 'top bar date badge missing');
  assert.ok(html.indexOf('class="status-label">News</span>') > -1, 'news status bar label missing');
  assert.ok(html.indexOf('id="newsTickerViewport"') > -1, 'news ticker viewport wrapper missing');
  assert.ok(html.indexOf('function setNewsTickerText(') > -1, 'news ticker update helper missing');
  assert.ok(html.indexOf("newsTickerNode.style.animation = 'none';") > -1, 'news ticker animation reset missing');
  assert.strictEqual(html.indexOf('body.takeover-solar .global-bar {\n      display: none;'), -1, 'solar takeover must keep global status bar visible');
  assert.ok(html.indexOf('body.takeover-solar #mainSolar {') > -1 && html.indexOf('top: var(--global-bar-clearance);') > -1, 'solar takeover panel should stay below status bar');
  assert.ok(html.indexOf('class="panel-title">Radar</span>') > -1, 'radar card title missing');
  assert.ok(html.indexOf('class="panel-title">Solar</span>') > -1, 'solar card title missing');
  assert.ok(html.indexOf('class="panel-title">Weather</span>') > -1, 'weather card title missing');
  assert.ok(html.indexOf('class="panel-title">Bins</span>') > -1, 'bins card title missing');
  assert.ok(html.indexOf('class="panel-title">Clock</span>') > -1, 'clock card title missing');
  assert.ok(html.indexOf('body.takeover-radar #mainRadar .panel-title') > -1, 'radar takeover title hide rule missing');
  assert.ok(html.indexOf('id="weatherForecast"') > -1, 'weather forecast section missing');
  assert.ok(html.indexOf('--font-display') > -1, 'font token system missing');
  assert.ok(html.indexOf('--font-ui') > -1, 'professional ui font token missing');
  assert.ok(html.indexOf('Manrope') > -1, 'professional heading font missing');
  assert.ok(html.indexOf('--bg-panel') > -1, 'new dark panel palette missing');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.34fr;') > -1, 'top row should reclaim more vertical space');
  assert.ok(html.indexOf('@media (max-width: 1100px) and (max-height: 820px) and (min-height: 700px) and (orientation: landscape)') > -1, 'tablet landscape breakpoint missing');
  assert.ok(html.indexOf('grid-template-columns: 1.7fr 1fr 1fr;') > -1, 'tablet bottom row ratio should favor weather panel');
  assert.ok(html.indexOf('animation-duration: 52s;') > -1, 'tablet ticker should scroll slower for readability');
  assert.ok(html.indexOf('--global-bar-clearance: 62px;') > -1, 'tablet clearance should reclaim vertical space after readability pass');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.45fr;') > -1, 'tablet row split should reduce dead gap while preserving larger lower metrics');
  assert.ok(html.indexOf('#mainRadar {\n        min-width: 0;\n      }') > -1, 'tablet radar panel should allow shrink to prevent edge stripe');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 1.32fr) minmax(0, 0.78fr);') > -1, 'tablet weather layout should prioritize current conditions width');
  assert.ok(html.indexOf('#timeBig {\n        font-size: 66px;') > -1, 'tablet clock should be more legible at distance');
  assert.ok(html.indexOf('.solar-gauge canvas {\n      width: 108px;') > -1, 'solar gauges should keep enough size for in-gauge detail text while preserving lower-card room');
  assert.ok(html.indexOf('min-height: 112px;') > -1, 'solar top gauge cards should be shorter to avoid truncating lower solar cards');
  assert.ok(html.indexOf('class="solar-gauge solar-gauge-generation skeleton"') > -1, 'generation gauge should use dedicated gauge class');
  assert.ok(html.indexOf('solar-gauge solar-gauge-usage') > -1, 'usage/import gauge should use dedicated gauge class');
  assert.ok(html.indexOf('.g-overlay {') > -1, 'gauge overlay text layer should exist');
  assert.ok(html.indexOf('id="generationGaugeText"') > -1, 'generation gauge overlay node missing');
  assert.ok(html.indexOf('id="usageGaugeText"') > -1, 'usage gauge overlay node missing');
  assert.ok(html.indexOf('font-size: clamp(22px, 3.9vh, 32px);') > -1, 'gauge primary text should be larger for distance readability');
  assert.ok(html.indexOf('-webkit-text-stroke: 1.6px rgba(5, 8, 12, 0.98);') > -1, 'gauge primary text needs stronger border contrast');
  assert.ok(html.indexOf('0 0 14px rgba(0, 0, 0, 0.7),') > -1, 'gauge text should include a stronger outer glow/halo');
  assert.ok(html.indexOf('-webkit-text-stroke: 1.2px rgba(5, 8, 12, 0.95);') > -1, 'gauge secondary text needs a stronger border contrast');
  assert.strictEqual(html.indexOf('.g-value {'), -1, 'legacy side-value gauge text should be removed');
  assert.ok(html.indexOf('.solar-status-card {\n        min-height: 86px;') > -1, 'tablet solar status cards should be larger for readability');
  assert.ok(html.indexOf('.solar-status-value {\n        font-size: 40px;') > -1, 'tablet solar status values should be larger');
  assert.ok(html.indexOf('#binsIcon {\n      position: absolute;') > -1, 'bins icon should become large background glyph');
  assert.ok(html.indexOf('font-size: 116px;') > -1, 'tablet bins icon should be oversized');
  assert.ok(html.indexOf('opacity: 0.32;') > -1, 'tablet bins icon should be subdued behind text');
  assert.ok(html.indexOf('#customCard {\n      display: flex;\n      flex-direction: column;\n      justify-content: center;\n      align-items: center;\n      text-align: center;') > -1, 'clock card should be center-aligned');
  assert.ok(html.indexOf('#weatherSummary {\n        font-size: clamp(20px, 3.3vh, 25px);') > -1, 'tablet weather summary should be larger');
  assert.ok(html.indexOf('.weather-temp-large {\n        font-size: clamp(34px, 5.4vh, 46px);') > -1, 'tablet weather temperature should be much larger');
  assert.ok(html.indexOf('function loadMapTileWithFallback(z, x, y) {') > -1, 'radar map tile fallback helper missing');
  assert.ok(html.indexOf('function loadMapTileFromLowerZoom(z, x, y) {') > -1, 'radar map tile fallback should support lower-zoom parent tiles');

  assert.ok(html.indexOf('id="solarChartsRow"') > -1, 'solar charts row container missing');
  assert.ok(html.indexOf('id="solarUsageChart"') > -1, 'primary solar usage chart canvas missing');
  assert.ok(html.indexOf('id="solarDawnChart"') > -1, 'solar dawn detail chart canvas missing');
  assert.ok(html.indexOf('id="solarFlowPanel"') > -1, 'solar flow summary panel missing');
  assert.ok(html.indexOf('id="solarFlowProduced"') > -1, 'solar flow produced metric missing');
  assert.ok(html.indexOf('id="solarFlowSelfUsed"') > -1, 'solar flow self-used metric missing');
  assert.ok(html.indexOf('id="solarFlowFeedIn"') > -1, 'solar flow feed-in metric missing');
  assert.ok(html.indexOf('id="solarFlowImport"') > -1, 'solar flow import metric missing');
  assert.ok(html.indexOf('id="solarFlowSelfPct"') > -1, 'solar flow self-consumption metric missing');
  assert.ok(html.indexOf('id="solarDataQualityBadge"') > -1, 'solar data-quality badge missing');
  assert.strictEqual(html.indexOf('id="solarBarChart"'), -1, 'legacy second solar chart should be removed');
  assert.ok(html.indexOf('min-height: 120px;') > -1, 'solar chart cards should be taller in main dashboard view');
  assert.ok(html.indexOf('height: 162px;') > -1, 'solar chart canvas should be ~20% taller in main dashboard view');
  assert.ok(html.indexOf('body.takeover-solar .chart-wrap {\n      height: 324px;') > -1, 'solar chart card should be doubled in takeover/fullscreen mode');
  assert.ok(html.indexOf('body.takeover-solar .chart {\n      height: 324px;') > -1, 'solar chart canvas should be doubled in takeover/fullscreen mode');
  assert.ok(html.indexOf('id="solarUsageLegend"') > -1, 'solar usage chart legend container missing');
  assert.ok(html.indexOf('Generated') > -1, 'solar usage chart legend should include generated series');
  assert.ok(html.indexOf('Self-used') > -1, 'solar usage chart legend should include self-used series');
  assert.ok(html.indexOf('Import') > -1, 'solar usage chart legend should include import series');
  assert.ok(html.indexOf('id="solarStatusGrid"') > -1, 'solar status grid missing');
  assert.ok(html.indexOf('class="solar-status-card"') > -1, 'solar status cards missing');
  assert.strictEqual(html.indexOf('id="solarFooter"'), -1, 'legacy solar footer status line should be removed');
  assert.ok(html.indexOf('min-height: 80px;') > -1, 'solar daily cards should fit with legend while staying readable');
  assert.ok(html.indexOf('.solar-status-label {\n      font-size: 12px;') > -1, 'solar status labels should be tightened to prevent clipping');
  assert.ok(html.indexOf('.solar-status-value {\n      font-family: var(--font-ui);\n      font-size: 26px;') > -1, 'solar status values should be reduced to prevent clipping');
  assert.ok(html.indexOf('padding: 7px 8px;') > -1, 'solar status cards should use tighter padding to avoid clipping');
  assert.ok(html.indexOf('id="weatherMainRow"') > -1, 'weather main row layout missing');
  assert.ok(html.indexOf('weather-now-panel') > -1, 'weather current panel treatment missing');
  assert.ok(html.indexOf('class="weather-current weather-now-panel"') > -1, 'weather card should use featured current panel');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 1.12fr) minmax(0, 1fr);') > -1, 'weather row should prioritize current conditions width');
  assert.ok(html.indexOf('font-size: clamp(13px, 2vh, 16px);') > -1, 'weather summary should remain readable while current temp grows');
  assert.ok(html.indexOf('font-size: clamp(38px, 5.7vh, 52px);') > -1, 'weather temperature should be larger for at-distance readability');
  assert.ok(html.indexOf('weather-temp-large') > -1, 'large weather temperature style missing');
  assert.ok(html.indexOf('#weatherCard {') > -1 && html.indexOf('grid-template-rows: 1fr;') > -1, 'weather card should use full height without title row');
  assert.ok(html.indexOf('padding: 10px 10px;') > -1, 'forecast cards should use compact padding');
  assert.ok(html.indexOf('font-size: 14px;') > -1, 'forecast temperature should stay compact');
  assert.ok(html.indexOf('min-height: 0;') > -1, 'forecast layout should include truncation guards');
  assert.ok(html.indexOf('font-size: 128px;') > -1, 'bin icon should be a large background glyph for distance readability');
  assert.ok(html.indexOf('id="binDetails"') > -1, 'bin details wrapper missing');
  assert.ok(html.indexOf('#binCard {\n      display: grid;\n      grid-template-columns: 1fr;') > -1, 'bin card should use a background icon layout');
  assert.ok(html.indexOf('#binCard.bin-card-today #binsType {') > -1, 'today bins type style override missing');
  assert.ok(html.indexOf('#binCard.bin-card-today #binsDate {') > -1, 'today bins subtitle style override missing');
  assert.ok(html.indexOf("binCardNode.classList.toggle('bin-card-today',") > -1, 'today bins class toggle missing');
  assert.ok(html.indexOf('#f2d44b') > -1, 'recycle bin icon should use yellow tone');
  assert.ok(html.indexOf('id="radarGifImage"') > -1, 'radar gif layer missing');
  assert.ok(html.indexOf('object-fit: cover;') > -1, 'radar gif should fill the viewport to remove side banding');
  assert.ok(html.indexOf('#radarGifImage {\n      position: absolute;') > -1 && html.indexOf('transform: none;') > -1, 'radar gif should not zoom so bottom timestamp stays visible');
  assert.ok(html.indexOf('function initRadarGifMode(') > -1, 'radar GIF init function should exist');
  assert.ok(html.indexOf('var radarGifViewportSig = \'\';') > -1, 'radar gif viewport signature cache missing');
  assert.ok(html.indexOf('var radarGifLastUpdatedAt = \'\';') > -1, 'radar gif realtime update marker missing');
  assert.ok(html.indexOf('var radarGifReloadQueued = false;') > -1, 'radar gif queued reload flag missing');
  assert.ok(html.indexOf('var radarGifReloadForceQueued = false;') > -1, 'radar gif queued force-reload flag missing');
  assert.ok(html.indexOf('function refreshRadarGifMode(') > -1, 'radar GIF viewport refresh helper missing');
  assert.ok(html.indexOf('refreshRadarGifMode(false);') > -1, 'resize path should refresh radar GIF dimensions');
  assert.ok(html.indexOf("patch.radar && patch.radar.gifUpdatedAt") > -1, 'realtime state should inspect radar gif update timestamp');
  assert.ok(html.indexOf('if (gifUpdatedAt && gifUpdatedAt !== radarGifLastUpdatedAt) {') > -1, 'gif reload should only trigger on update timestamp changes');
  assert.ok(html.indexOf('radarGifReloadQueued = true;') > -1, 'gif update should queue reload when image is already loading');
  assert.ok(html.indexOf('if (radarGifReloadQueued) {') > -1, 'gif onload/onerror should flush queued reload');
  assert.ok(html.indexOf('function loadRadarGif(force) {') > -1, 'gif loader should support forced reloads');
  assert.strictEqual(html.indexOf("src += (src.indexOf('?') > -1 ? '&' : '?') + 'strict=1';"), -1, 'gif loader should not force strict rendering reloads');
  assert.ok(html.indexOf('if (radarGifLoading) {') > -1, 'gif loader should guard against concurrent in-flight requests');
  assert.ok(html.indexOf('radarGifReloadForceQueued = radarGifReloadForceQueued || !!force;') > -1, 'queued reload should preserve force intent');
  assert.ok(html.indexOf('var queuedForce = radarGifReloadForceQueued;') > -1, 'gif onload/onerror should drain queued force mode');
  assert.ok(html.indexOf('loadRadarGif(false);') > -1, 'realtime gif updates should request latest gif without strict blocking');
  assert.ok(html.indexOf('function loadRadarGif(') > -1, 'radar GIF load function should exist');
  assert.ok(html.indexOf('function maybeStartRadarLoop(') > -1, 'radar startup loop gate missing');
  assert.ok(html.indexOf('requestAnimationFrame(animateRadar);') > -1, 'radar startup should launch canvas animation loop immediately');
  assert.ok(html.indexOf('id="radarGifStatus"') > -1, 'radar GIF status indicator missing');
  assert.ok(html.indexOf('function updateRadarGifStatus(') > -1, 'radar GIF status updater missing');
  assert.ok(html.indexOf("if (radarRenderMode === 'gif') {") > -1, 'gif mode should short-circuit png tile rendering');
  assert.ok(html.indexOf('Radar animation generating...') > -1, 'gif mode should render loading message without png tile fetches');
  assert.ok(html.indexOf('radarGifImage.onload') > -1, 'gif readiness promotion missing');
  assert.ok(html.indexOf('function classifyRadarRain(') > -1, 'radar rain classification helper missing');
  assert.ok(html.indexOf('var isYellow = (r > 150 && g > 130 && b < 160);') > -1, 'radar classifier should detect yellow precipitation echoes');
  assert.ok(html.indexOf('Heavy rain nearby') > -1, 'heavy rain indicator message missing');
  assert.ok(html.indexOf('importReady') > -1, 'solar import readiness gating missing');
  assert.ok(html.indexOf('function isSolarBackendPending(') > -1, 'solar backend pending helper missing');
  assert.ok(html.indexOf('isSolarBackendPending(state.fronius || {})') > -1, 'solar loading should depend on backend readiness while data is zero');
  assert.ok(html.indexOf("document.getElementById('solarStatusImport').textContent = importReady") > -1, 'solar import display should use readiness');
  assert.ok(html.indexOf('function sumSolarBinsKwh(') > -1, 'solar daily bins helper missing');
  assert.ok(html.indexOf('today.importReady && Number(today.importKwh || 0) > 0') > -1, 'solar data detection should ignore unready import estimates');
  assert.ok(html.indexOf('today.generatedReady && Number(today.generatedKwh || 0) > 0') > -1, 'solar data detection should respect generated readiness');
  assert.ok(html.indexOf('function hasAnySolarBinEnergy(') > -1, 'solar bins energy helper missing');
  assert.ok(html.indexOf('var todayHasTotals = Number(todayRaw.generatedKwh || 0) > 0 || Number(todayRaw.importKwh || 0) > 0 || Number(todayRaw.exportKwh || 0) > 0;') > -1, 'solar chart loading should consider non-zero totals while bins are empty');
  assert.ok(html.indexOf('var chartsLoading = !binsHaveEnergy && (isSolarBackendPending(state.fronius || {}) || todayHasTotals);') > -1, 'solar charts should stay in loading mode until bins are populated');
  assert.ok(html.indexOf('function drawHourAxis(') > -1, 'solar chart hour axis helper missing');
  assert.ok(html.indexOf('for (var hour = 0; hour <= 21; hour += 3)') > -1, 'solar chart should label hours every 3');
  assert.ok(html.indexOf('var slot = (hour / 24) * count;') > -1, 'solar hour ticks should map against rendered bar count');
  assert.ok(html.indexOf('drawHourAxis(ctx, w, h, pad, chartBottom, barsCount, barW);') > -1, 'solar hour axis should align to fixed bar geometry');
  assert.ok(html.indexOf('function drawLoadingBars(') > -1, 'solar loading chart helper missing');
  assert.ok(html.indexOf("ctx.fillStyle = '#5fe08b';") > -1, 'solar feed-in bars should use green highlight');
  assert.ok(html.indexOf('rgba(126, 225, 160') > -1, 'solar loading bars should use green tone');
  assert.ok(html.indexOf('setSolarChartsLoading(chartsLoading);') > -1, 'solar loading chart toggling missing');
  assert.ok(html.indexOf('function drawUsageHourlyBars(') > -1, 'usage hourly draw helper missing');
  assert.ok(html.indexOf('function drawGeneratedLine(') > -1, 'generated line helper missing for hybrid chart');
  assert.strictEqual(html.indexOf('function smoothSeries('), -1, 'generated line should avoid averaging helper');
  assert.ok(html.indexOf("ctx.strokeStyle = '#ff6a1a';") > -1, 'generated hybrid line color should be orange-red for stronger contrast');
  assert.ok(html.indexOf('ctx.lineWidth = 4;') > -1, 'generated hybrid line should be thicker');
  assert.ok(html.indexOf("ctx.lineJoin = 'round';") > -1, 'generated hybrid line should use rounded joins');
  assert.ok(html.indexOf("ctx.lineCap = 'round';") > -1, 'generated hybrid line should use rounded caps');
  assert.strictEqual(html.indexOf('ctx.quadraticCurveTo('), -1, 'generated hybrid line should avoid curve interpolation');
  assert.ok(html.indexOf('var usagePeakWh = 1;') > -1, 'usage bars should track usage peak independently');
  assert.ok(html.indexOf('usagePeakWh = Math.max(usagePeakWh, Number(item.selfWh || 0) + Number(item.importWh || 0));') > -1, 'usage bars should scale from self+import stack only');
  assert.ok(html.indexOf('var generatedLinePeakWh = generatedSeries.reduce(function (peak, value) { return Math.max(peak, Number(value || 0)); }, 0);') > -1, 'generated line scale should derive peak from raw values');
  assert.ok(html.indexOf('var generatedCapWh = 6000 * 1.02;') > -1, 'generated line scaling should cap at 6kW plus headroom');
  assert.ok(html.indexOf('var generatedLineMaxY = Math.min(generatedCapWh, Math.max(1, generatedLinePeakWh * 1.02));') > -1, 'generated line should use dynamic peak scale with cap');
  assert.ok(html.indexOf('.solar-gauge-usage.is-no-import') > -1, 'usage/import gauge should expose no-import state class');
  assert.ok(html.indexOf('.solar-gauge-usage.is-importing') > -1, 'usage/import gauge should expose importing state class');
  assert.ok(html.indexOf('.solar-gauge-generation.is-maxed') > -1, 'generation gauge should expose maxed pulse state class');
  assert.ok(html.indexOf('#generationGaugeText,\n    #generationGaugeText .g-overlay-main,\n    #generationGaugeText .g-overlay-sub {\n      color: #00ff3d') > -1, 'generation gauge text should always be green');
  assert.ok(html.indexOf('#usageGaugeText.is-no-import') > -1, 'usage gauge text should expose no-import state class');
  assert.ok(html.indexOf('#usageGaugeText.is-importing') > -1, 'usage gauge text should expose importing state class');
  assert.ok(html.indexOf("usageGaugeNode.classList.toggle('is-importing', importW > 0.02);") > -1, 'usage gauge should switch to import state when importing');
  assert.ok(html.indexOf("usageGaugeTextNode.classList.toggle('is-importing', importW > 0.02);") > -1, 'usage gauge text should switch to import state when importing');
  assert.ok(html.indexOf("generationGaugeNode.classList.toggle('is-maxed', genW >= capW * 0.98);") > -1, 'generation gauge should pulse when near inverter max');
  assert.ok(html.indexOf('function drawDawnQuarterBars(') > -1, 'dawn quarter draw helper missing');
  assert.ok(html.indexOf('function buildSolarPanelSignatures(') > -1, 'solar panel signature helper missing');
  assert.ok(html.indexOf('if (panelSigs.usage !== lastSolarUsageSig) {') > -1, 'usage panel redraw guard missing');
  assert.ok(html.indexOf('if (panelSigs.dawn !== lastSolarDawnSig) {') > -1, 'dawn panel redraw guard missing');
  assert.ok(html.indexOf('if (panelSigs.flow !== lastSolarFlowSig) {') > -1, 'flow panel redraw guard missing');
  assert.ok(html.indexOf("solarDataQuality === 'realtime_estimated'") > -1, 'estimated data-quality branch missing');
  assert.strictEqual(html.indexOf('function reduceBinsForChart('), -1, 'legacy chart reduction helper should be removed');
  assert.ok(html.indexOf('var stateFetchInFlight = false;') > -1, 'state fetch overlap guard missing');
  assert.ok(html.indexOf('if (stateFetchInFlight) { return; }') > -1, 'state fetch throttle branch missing');
  assert.ok(html.indexOf('var radarLoopStarted = false;') > -1, 'deferred radar startup flag missing');
  assert.ok(html.indexOf('if (radarLoopStarted || !firstDataApplied) {') > -1, 'deferred radar startup guard missing');
  assert.ok(html.indexOf('requestAnimationFrame(animateRadar);\n        initRadarGifMode();') === -1, 'startup should not kick off png tile animation loop');
  assert.ok(html.indexOf('if (payload.gifPath) {') > -1, 'radar gif init should always use gifPath regardless of mode');
  assert.ok(html.indexOf('window.location.replace(buildViewUrl(viewMode, untilMs, nextAtMs));') > -1, 'fullscreen switch should force a page reload');
  assert.ok(html.indexOf("document.body.classList.add('blackout');") > -1, 'fullscreen switch should enable blackout overlay');
  assert.ok(html.indexOf('setTimeout(function () {\n          reloadToView(viewMode, untilMs, nextAtMs);\n        }, TAKEOVER_BLACKOUT_MS);') > -1, 'fullscreen transition should delay reload to show blackout');
  assert.ok(html.indexOf('transitionReloadToView(mode === \'radar\' ? \'radar\' : \'solar\', now + durationMs, nextAtMs);') > -1, 'takeover start should use blackout transition');
  assert.ok(html.indexOf('transitionReloadToView(\'main\', 0, nextAtMs);') > -1, 'takeover end should use blackout transition');
  assert.ok(html.indexOf("var lastFocusMode = '';") > -1, 'focus rotation should persist last mode across reloads');
  assert.ok(html.indexOf("lastFocusMode = normalizeFocusMode(search.get('lastfocus'));") > -1, 'initial view parsing should restore last focus mode from URL');
  assert.ok(html.indexOf("url.searchParams.set('lastfocus', lastFocusMode);") > -1, 'view reload URL should carry last focus mode');
  assert.ok(html.indexOf("var lastIdx = views.indexOf(lastFocusMode);") > -1, 'next takeover picker should reference last focus mode');
  assert.ok(html.indexOf('return views[(lastIdx + 1) % views.length];') > -1, 'next takeover picker should advance past previous focus mode');
  assert.ok(html.indexOf('lastFocusMode = mode;') > -1, 'begin takeover should update last focus mode before reload');
  assert.ok(html.indexOf('function applyTimeOfDayTheme(') > -1, 'time-of-day color helper missing');
  assert.ok(html.indexOf("document.body.classList.remove('time-night', 'time-twilight', 'time-day');") > -1, 'time-of-day class reset missing');
  assert.ok(html.indexOf('body.time-night #timeBig') > -1, 'night time color style missing');
  assert.ok(html.indexOf('body.time-twilight #timeBig') > -1, 'twilight time color style missing');
  assert.ok(html.indexOf('body.time-day #timeBig') > -1, 'day time color style missing');
  assert.ok(html.indexOf('function formatDateShort(') > -1, 'short date formatter missing');
  assert.ok(html.indexOf('ctx.imageSmoothingEnabled = false;') > -1, 'radar smoothing guard missing');
  assert.ok(html.indexOf('var radarClassifyCanvas = document.createElement(\'canvas\');') > -1, 'radar-only classification canvas missing');
  assert.ok(html.indexOf('if (!classified.hasSignal) {') > -1, 'radar low-signal fallback guard missing');
  assert.ok(html.indexOf('drawX: Math.round(') > -1, 'integer snapped tile draw coordinates missing');
};
