'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

module.exports = async function run() {
  const html = fs.readFileSync(path.join(process.cwd(), 'public/dashboard.html'), 'utf8');

  assert.ok(html.indexOf('id="globalRainIndicator"') > -1, 'global rain indicator missing');
  assert.strictEqual(html.indexOf('class="card-head"'), -1, 'legacy card header rows should be removed');
  assert.ok(html.indexOf('class="panel-corner-icon"') > -1, 'corner icon primitive missing');
  assert.ok(html.indexOf('class="card-icon"') > -1, 'card icon element missing');
  assert.ok(html.indexOf('id="mainRadar"') > -1, 'main radar panel missing');
  assert.ok(html.indexOf('id="mainSolar"') > -1, 'main solar panel missing');
  assert.ok(html.indexOf('id="customCard"') > -1, 'custom card placeholder missing');
  assert.ok(html.indexOf('id="takeoverBlackout"') > -1, 'takeover blackout layer missing');
  assert.ok(html.indexOf('id="topDateBadge"') > -1, 'top bar date badge missing');
  assert.ok(html.indexOf('class="status-label">News</span>') > -1, 'news status bar label missing');
  assert.ok(html.indexOf('id="newsTickerViewport"') > -1, 'news ticker viewport wrapper missing');
  assert.ok(html.indexOf('function setNewsTickerText(') > -1, 'news ticker update helper missing');
  assert.ok(html.indexOf("newsTickerNode.style.animation = 'none';") > -1, 'news ticker animation reset missing');
  assert.strictEqual(html.indexOf('body.takeover-solar .global-bar {\n      display: none;'), -1, 'solar takeover must keep global status bar visible');
  assert.ok(html.indexOf('body.takeover-solar #mainSolar {') > -1 && html.indexOf('top: var(--global-bar-clearance);') > -1, 'solar takeover panel should stay below status bar');
  assert.ok(html.indexOf('class="panel-title">Radar</span>') > -1, 'radar card title missing');
  assert.ok(html.indexOf('class="panel-title">Solar</span>') > -1, 'solar card title missing');
  assert.ok(html.indexOf('class="panel-title">Weather</span>') > -1, 'weather card title missing');
  assert.ok(html.indexOf('class="panel-title">Bins</span>') > -1, 'bins card title missing');
  assert.ok(html.indexOf('class="panel-title">Clock</span>') > -1, 'clock card title missing');
  assert.ok(html.indexOf('body.takeover-radar #mainRadar .panel-title') > -1, 'radar takeover title hide rule missing');
  assert.ok(html.indexOf('id="weatherForecast"') > -1, 'weather forecast section missing');
  assert.ok(html.indexOf('--font-display') > -1, 'font token system missing');
  assert.ok(html.indexOf('--font-ui') > -1, 'professional ui font token missing');
  assert.ok(html.indexOf('Manrope') > -1, 'professional heading font missing');
  assert.ok(html.indexOf('--bg-panel') > -1, 'new dark panel palette missing');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.34fr;') > -1, 'top row should reclaim more vertical space');
  assert.ok(html.indexOf('@media (max-width: 1100px) and (max-height: 820px) and (min-height: 700px) and (orientation: landscape)') > -1, 'tablet landscape breakpoint missing');
  assert.ok(html.indexOf('grid-template-columns: 1.7fr 1fr 1fr;') > -1, 'tablet bottom row ratio should favor weather panel');
  assert.ok(html.indexOf('animation-duration: 52s;') > -1, 'tablet ticker should scroll slower for readability');
  assert.ok(html.indexOf('--global-bar-clearance: 62px;') > -1, 'tablet clearance should reclaim vertical space after readability pass');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.45fr;') > -1, 'tablet row split should reduce dead gap while preserving larger lower metrics');
  assert.ok(html.indexOf('#mainRadar {\n        min-width: 0;\n      }') > -1, 'tablet radar panel should allow shrink to prevent edge stripe');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 1.32fr) minmax(0, 0.78fr);') > -1, 'tablet weather layout should prioritize current conditions width');
  assert.ok(html.indexOf('#timeBig {\n        font-size: 66px;') > -1, 'tablet clock should be more legible at distance');
  assert.ok(html.indexOf('.solar-gauge canvas {\n      width: 106px;') > -1, 'solar gauges should be enlarged for in-gauge detail text');
  assert.strictEqual(html.indexOf('.g-value {'), -1, 'legacy side-value gauge text should be removed');
  assert.ok(html.indexOf('.solar-status-card {\n        min-height: 86px;') > -1, 'tablet solar status cards should be larger for readability');
  assert.ok(html.indexOf('.solar-status-value {\n        font-size: 34px;') > -1, 'tablet solar status values should be larger');
  assert.ok(html.indexOf('#binsIcon {\n      position: absolute;') > -1, 'bins icon should become large background glyph');
  assert.ok(html.indexOf('font-size: 116px;') > -1, 'tablet bins icon should be oversized');
  assert.ok(html.indexOf('opacity: 0.2;') > -1, 'tablet bins icon should be subdued behind text');
  assert.ok(html.indexOf('#customCard {\n      display: flex;\n      flex-direction: column;\n      justify-content: center;\n      align-items: center;\n      text-align: center;') > -1, 'clock card should be center-aligned');
  assert.ok(html.indexOf('#weatherSummary {\n        font-size: clamp(20px, 3.3vh, 25px);') > -1, 'tablet weather summary should be larger');
  assert.ok(html.indexOf('.weather-temp-large {\n        font-size: clamp(34px, 5.4vh, 46px);') > -1, 'tablet weather temperature should be much larger');
  assert.ok(html.indexOf('function loadMapTileWithFallback(z, x, y) {') > -1, 'radar map tile fallback helper missing');
  assert.ok(html.indexOf('function loadMapTileFromLowerZoom(z, x, y) {') > -1, 'radar map tile fallback should support lower-zoom parent tiles');

  assert.ok(html.indexOf('id="solarChartsRow"') > -1, 'solar charts row container missing');
  assert.ok(html.indexOf('min-height: 104px;') > -1, 'solar chart cards should be tall while preserving room for lower KPIs');
  assert.ok(html.indexOf('height: 104px;') > -1, 'solar chart canvas should match the chart card height');
  assert.ok(html.indexOf('id="solarStatusGrid"') > -1, 'solar status grid missing');
  assert.ok(html.indexOf('class="solar-status-card"') > -1, 'solar status cards missing');
  assert.strictEqual(html.indexOf('id="solarFooter"'), -1, 'legacy solar footer status line should be removed');
  assert.ok(html.indexOf('min-height: 90px;') > -1, 'solar daily cards should be larger');
  assert.ok(html.indexOf('id="weatherMainRow"') > -1, 'weather main row layout missing');
  assert.ok(html.indexOf('weather-now-panel') > -1, 'weather current panel treatment missing');
  assert.ok(html.indexOf('class="weather-current weather-now-panel"') > -1, 'weather card should use featured current panel');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 1.12fr) minmax(0, 1fr);') > -1, 'weather row should prioritize current conditions width');
  assert.ok(html.indexOf('font-size: clamp(13px, 2vh, 16px);') > -1, 'weather summary should remain readable while current temp grows');
  assert.ok(html.indexOf('font-size: clamp(38px, 5.7vh, 52px);') > -1, 'weather temperature should be larger for at-distance readability');
  assert.ok(html.indexOf('weather-temp-large') > -1, 'large weather temperature style missing');
  assert.ok(html.indexOf('#weatherCard {') > -1 && html.indexOf('grid-template-rows: 1fr;') > -1, 'weather card should use full height without title row');
  assert.ok(html.indexOf('padding: 10px 10px;') > -1, 'forecast cards should use compact padding');
  assert.ok(html.indexOf('font-size: 14px;') > -1, 'forecast temperature should stay compact');
  assert.ok(html.indexOf('min-height: 0;') > -1, 'forecast layout should include truncation guards');
  assert.ok(html.indexOf('font-size: 128px;') > -1, 'bin icon should be a large background glyph for distance readability');
  assert.ok(html.indexOf('id="binDetails"') > -1, 'bin details wrapper missing');
  assert.ok(html.indexOf('#binCard {\n      display: grid;\n      grid-template-columns: 1fr;') > -1, 'bin card should use a background icon layout');
  assert.ok(html.indexOf('#f2d44b') > -1, 'recycle bin icon should use yellow tone');
  assert.ok(html.indexOf('id="radarGifImage"') > -1, 'radar gif layer missing');
  assert.ok(html.indexOf('object-fit: cover;') > -1, 'radar gif should fill the viewport to remove side banding');
  assert.ok(html.indexOf('transform: scale(1.05);') > -1, 'radar gif should be slightly zoomed for cleaner edges');
  assert.ok(html.indexOf('function fetchRadarAnimationMode(') > -1, 'radar animation mode fetch missing');
  assert.ok(html.indexOf('function warmRadarGif(') > -1, 'radar gif warmup hook missing');
  assert.ok(html.indexOf('var radarStartupHoldUntilMs = Date.now() + 6000;') > -1, 'radar startup gif hold window missing');
  assert.ok(html.indexOf('var radarAnimationModeKnown = false;') > -1, 'radar animation mode knowledge guard missing');
  assert.ok(html.indexOf("var radarPreferredMode = 'png';") > -1, 'radar preferred mode tracker missing');
  assert.ok(html.indexOf('var RADAR_GIF_STALE_TIMEOUT_MS = 5 * 60 * 1000;') > -1, 'radar stale gif timeout should be 5 minutes');
  assert.ok(html.indexOf('function maybeStartRadarLoop(') > -1, 'radar startup loop gate missing');
  assert.ok(html.indexOf("setRadarMode('png');") > -1, 'radar startup should force png mode to avoid blank screen while gif warms');
  assert.strictEqual(html.indexOf('if (!radarAnimationModeKnown) {'), -1, 'radar startup should not block on animation mode before drawing');
  assert.strictEqual(html.indexOf("if (radarPreferredMode === 'gif' && !radarGifReady && !radarStartupPrefetchDone && Date.now() < radarStartupHoldUntilMs) {"), -1, 'radar startup should not defer png while gif is pending');
  assert.ok(html.indexOf('function scheduleRadarStartupProbe(') > -1, 'radar startup probe scheduler missing');
  assert.ok(html.indexOf('[450, 1200, 2200, 3600, 5200]') > -1, 'radar startup probe timings missing');
  assert.ok(html.indexOf('radarGifImage.onload') > -1, 'gif readiness promotion missing');
  assert.ok(html.indexOf('radarGifLoadedOnce') > -1, 'radar gif continuity guard missing');
  assert.ok(html.indexOf("if (radarPreferredMode === 'gif' && Date.now() < radarStartupHoldUntilMs) {") > -1, 'startup gif errors should retry before png fallback');
  assert.ok(html.indexOf('setTimeout(function () {') > -1 && html.indexOf('warmRadarGif(true);') > -1, 'startup gif retry timer missing');
  assert.ok(html.indexOf('if (!radarGifLoadedOnce && Date.now() < radarStartupHoldUntilMs) {') > -1, 'animation mode fetch errors should not immediately force png');
  assert.ok(html.indexOf("radarGifImage.src = radarGifPath + sep + 'strict=1&_=' + now;") > -1, 'gif warm requests should enforce strict freshness checks');
  assert.ok(html.indexOf('function classifyRadarRain(') > -1, 'radar rain classification helper missing');
  assert.ok(html.indexOf('Heavy rain nearby') > -1, 'heavy rain indicator message missing');
  assert.ok(html.indexOf('importReady') > -1, 'solar import readiness gating missing');
  assert.ok(html.indexOf('function isSolarBackendPending(') > -1, 'solar backend pending helper missing');
  assert.ok(html.indexOf('isSolarBackendPending(state.fronius || {})') > -1, 'solar loading should depend on backend readiness while data is zero');
  assert.ok(html.indexOf("document.getElementById('solarStatusImport').textContent = importReady") > -1, 'solar import display should use readiness');
  assert.ok(html.indexOf('function sumSolarBinsKwh(') > -1, 'solar daily bins helper missing');
  assert.ok(html.indexOf('today.importReady && Number(today.importKwh || 0) > 0') > -1, 'solar data detection should ignore unready import estimates');
  assert.ok(html.indexOf('today.generatedReady && Number(today.generatedKwh || 0) > 0') > -1, 'solar data detection should respect generated readiness');
  assert.ok(html.indexOf('function hasAnySolarBinEnergy(') > -1, 'solar bins energy helper missing');
  assert.ok(html.indexOf('var todayHasTotals = Number(todayRaw.generatedKwh || 0) > 0 || Number(todayRaw.importKwh || 0) > 0 || Number(todayRaw.exportKwh || 0) > 0;') > -1, 'solar chart loading should consider non-zero totals while bins are empty');
  assert.ok(html.indexOf('var chartsLoading = !binsHaveEnergy && (isSolarBackendPending(state.fronius || {}) || todayHasTotals);') > -1, 'solar charts should stay in loading mode until bins are populated');
  assert.ok(html.indexOf('function drawHourAxis(') > -1, 'solar chart hour axis helper missing');
  assert.ok(html.indexOf('for (var hour = 0; hour <= 21; hour += 3)') > -1, 'solar chart should label hours every 3');
  assert.ok(html.indexOf('var slot = (hour / 24) * count;') > -1, 'solar hour ticks should map against rendered bar count');
  assert.ok(html.indexOf('drawHourAxis(ctx, w, h, pad, chartBottom, data.length, barW);') > -1, 'solar hour axis should align to bar geometry');
  assert.ok(html.indexOf('function drawLoadingBars(') > -1, 'solar loading chart helper missing');
  assert.ok(html.indexOf("'#f2bb3c', '#5fe08b'") > -1, 'solar feed-in bars should use green highlight');
  assert.ok(html.indexOf('rgba(126, 225, 160') > -1, 'solar loading bars should use green tone');
  assert.ok(html.indexOf('setSolarChartsLoading(chartsLoading);') > -1, 'solar loading chart toggling missing');
  assert.ok(html.indexOf('function buildBinsSignature(') > -1, 'solar bins signature helper missing');
  assert.ok(html.indexOf('function reduceBinsForChart(') > -1, 'solar chart reduction helper missing');
  assert.ok(html.indexOf('function scheduleSolarBarsDraw(') > -1, 'solar bars scheduling helper missing');
  assert.ok(html.indexOf('if (solarBarsDrawScheduled) {') > -1, 'solar bars scheduling guard missing');
  assert.ok(html.indexOf('var maxBars = Math.max(12, Math.min(24') > -1, 'solar bars max cap optimization missing');
  assert.ok(html.indexOf('if (barsSig !== lastSolarBarsSig) {') > -1, 'solar bars redraw guard missing');
  assert.ok(html.indexOf('var stateFetchInFlight = false;') > -1, 'state fetch overlap guard missing');
  assert.ok(html.indexOf('if (stateFetchInFlight) { return; }') > -1, 'state fetch throttle branch missing');
  assert.ok(html.indexOf('var radarLoopStarted = false;') > -1, 'deferred radar startup flag missing');
  assert.ok(html.indexOf('if (radarLoopStarted || !firstDataApplied) {') > -1, 'deferred radar startup guard missing');
  assert.ok(html.indexOf('function applyTimeOfDayTheme(') > -1, 'time-of-day color helper missing');
  assert.ok(html.indexOf("document.body.classList.remove('time-night', 'time-twilight', 'time-day');") > -1, 'time-of-day class reset missing');
  assert.ok(html.indexOf('body.time-night #timeBig') > -1, 'night time color style missing');
  assert.ok(html.indexOf('body.time-twilight #timeBig') > -1, 'twilight time color style missing');
  assert.ok(html.indexOf('body.time-day #timeBig') > -1, 'day time color style missing');
  assert.ok(html.indexOf('function formatDateShort(') > -1, 'short date formatter missing');
  assert.ok(html.indexOf('ctx.imageSmoothingEnabled = false;') > -1, 'radar smoothing guard missing');
  assert.ok(html.indexOf('var radarClassifyCanvas = document.createElement(\'canvas\');') > -1, 'radar-only classification canvas missing');
  assert.ok(html.indexOf('if (!classified.hasSignal) {') > -1, 'radar low-signal fallback guard missing');
  assert.ok(html.indexOf('drawX: Math.round(') > -1, 'integer snapped tile draw coordinates missing');
};
