'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

module.exports = async function run() {
  const html = fs.readFileSync(path.join(process.cwd(), 'public/dashboard.html'), 'utf8');

  assert.ok(html.indexOf('id="globalRainIndicator"') > -1, 'global rain indicator missing');
  assert.strictEqual(html.indexOf('class="card-head"'), -1, 'legacy card header rows should be removed');
  assert.ok(html.indexOf('class="panel-corner-icon"') > -1, 'corner icon primitive missing');
  assert.ok(html.indexOf('class="card-icon"') > -1, 'card icon element missing');
  assert.ok(html.indexOf('id="mainRadar"') > -1, 'main radar panel missing');
  assert.ok(html.indexOf('id="mainSolar"') > -1, 'main solar panel missing');
  assert.ok(html.indexOf('id="customCard"') > -1, 'custom card placeholder missing');
  assert.ok(html.indexOf('id="takeoverBlackout"') > -1, 'takeover blackout layer missing');
  assert.ok(html.indexOf('id="topDateBadge"') > -1, 'top bar date badge missing');
  assert.ok(html.indexOf('class="status-label">News</span>') > -1, 'news status bar label missing');
  assert.ok(html.indexOf('id="newsTickerViewport"') > -1, 'news ticker viewport wrapper missing');
  assert.ok(html.indexOf('function setNewsTickerText(') > -1, 'news ticker update helper missing');
  assert.ok(html.indexOf("newsTickerNode.style.animation = 'none';") > -1, 'news ticker animation reset missing');
  assert.strictEqual(html.indexOf('body.takeover-solar .global-bar {\n      display: none;'), -1, 'solar takeover must keep global status bar visible');
  assert.ok(html.indexOf('body.takeover-solar #mainSolar {') > -1 && html.indexOf('top: var(--global-bar-clearance);') > -1, 'solar takeover panel should stay below status bar');
  assert.ok(html.indexOf('class="panel-title">Radar</span>') > -1, 'radar card title missing');
  assert.ok(html.indexOf('class="panel-title">Solar</span>') > -1, 'solar card title missing');
  assert.ok(html.indexOf('class="panel-title">Weather</span>') > -1, 'weather card title markup missing');
  assert.ok(html.indexOf('#weatherStripPanel .panel-corner-icon,\n    #weatherStripPanel .panel-title {\n      display: none;') > -1, 'weather strip should hide panel header chrome');
  assert.ok(html.indexOf('class="panel-title">Bins</span>') > -1, 'bins card title missing');
  assert.ok(html.indexOf('id="weatherBinsStripViewport"') > -1, 'combined weather/bins strip viewport missing');
  assert.ok(html.indexOf('id="weatherBinsStripTrack"') > -1, 'combined weather/bins strip track missing');
  assert.ok(html.indexOf('.strip-card-bg-icon {') > -1, 'strip weather cards should support a background icon');
  assert.ok(html.indexOf('class="strip-card-bg-icon is-hero">') > -1, 'weather now strip card should render a hero background icon');
  assert.ok(html.indexOf('.strip-card-bg-icon.is-hero') > -1, 'strip cards should support centered hero background icons');
  assert.ok(html.indexOf('.strip-card > :not(.strip-card-bg-icon) {\n      position: relative;\n      z-index: 1;') > -1, 'strip content should stay above the background icon');
  assert.ok(html.indexOf('.strip-card {\n      width: 196px;') > -1, 'strip cards should be narrower to avoid truncation');
  assert.ok(html.indexOf('.strip-card {\n      width: 196px;\n      min-height: 100%;\n      border-radius: 14px;\n      border: 1px solid rgba(114, 128, 148, 0.34);\n      background: rgba(14, 18, 24, 0.84);\n      padding: 8px 9px;\n      position: relative;') > -1, 'strip cards should anchor absolute background icons inside each card');
  assert.ok(html.indexOf('.strip-card.strip-card-stack {\n      align-content: stretch;\n      grid-template-rows: auto auto minmax(0, 1fr);\n      gap: 3px;') > -1, 'regular strip cards should use a consistent compact top-anchored stack layout');
  assert.ok(html.indexOf('.strip-card.strip-card-weather-now {\n      align-content: stretch;\n      grid-template-rows: auto auto minmax(0, 1fr);') > -1, 'weather now cards should keep the header and summary at the top with the value centered below');
  assert.ok(html.indexOf('.strip-card.strip-card-weather-now .strip-card-value {\n      align-self: center;\n      justify-self: center;') > -1, 'weather now temperature should sit on the vertical midline and center on the icon');
  assert.ok(html.indexOf('.strip-card.strip-card-bin {\n      width: 220px;') > -1, 'bin strip cards should be narrower to avoid truncation');
  assert.ok(html.indexOf(".strip-card.strip-card-bin.strip-tone-yellow {\n      background: linear-gradient(180deg, rgba(255, 243, 176, 0.16), rgba(255, 243, 176, 0.05)), rgba(34, 28, 10, 0.84);") > -1, 'recycle bin cards should use a yellow-tinted background');
  assert.ok(html.indexOf(".strip-card.strip-card-bin.strip-tone-blue {\n      background: linear-gradient(180deg, rgba(160, 214, 255, 0.16), rgba(160, 214, 255, 0.05)), rgba(11, 21, 34, 0.84);") > -1, 'other bin cards should use a blue-tinted background');
  assert.ok(html.indexOf('grid-template-rows: auto 1fr auto auto auto 1fr;') > -1, 'bin strip cards should keep the kicker at the top and center the main content');
  assert.ok(html.indexOf('.strip-card-bg-icon.is-hero {\n      opacity: 0.16;') > -1, 'hero background icons should use the same transparency as other cards');
  assert.ok(html.indexOf('font-size: 18px;') > -1, 'strip titles should be reduced further to fit the card height');
  assert.ok(html.indexOf('font-size: 28px;') > -1, 'strip value text should be reduced further to fit the card height');
  assert.ok(html.indexOf('symbol id="i-recycle"') > -1, 'recycle svg symbol missing');
  assert.ok(html.indexOf('class="panel-title">Clock</span>') > -1, 'clock card title missing');
  assert.ok(html.indexOf('body.takeover-radar #mainRadar .panel-title') > -1, 'radar takeover title hide rule missing');
  assert.ok(html.indexOf('id="weatherForecast"') > -1, 'weather forecast section missing');
  assert.ok(html.indexOf('--font-display') > -1, 'font token system missing');
  assert.ok(html.indexOf('--font-ui') > -1, 'professional ui font token missing');
  assert.ok(html.indexOf('Manrope') > -1, 'professional heading font missing');
  assert.ok(html.indexOf('--bg-panel') > -1, 'new dark panel palette missing');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.34fr;') > -1, 'top row should reclaim more vertical space');
  assert.ok(html.indexOf('@media (max-width: 1100px) and (max-height: 820px) and (min-height: 700px) and (orientation: landscape)') > -1, 'tablet landscape breakpoint missing');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 2.2fr) minmax(0, 1fr);') > -1, 'tablet bottom row should use a wide strip plus fixed clock');
  assert.ok(html.indexOf('animation-duration: 52s;') > -1, 'tablet ticker should scroll slower for readability');
  assert.ok(html.indexOf('--global-bar-clearance: 62px;') > -1, 'tablet clearance should reclaim vertical space after readability pass');
  assert.ok(html.indexOf('grid-template-rows: 1fr 0.45fr;') > -1, 'tablet row split should reduce dead gap while preserving larger lower metrics');
  assert.ok(html.indexOf('#mainRadar {\n        min-width: 0;\n      }') > -1, 'tablet radar panel should allow shrink to prevent edge stripe');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 0.92fr) minmax(0, 1.08fr);') > -1, 'tablet weather layout should prioritize forecast width');
  assert.ok(html.indexOf('#timeBig {\n        font-size: 66px;') > -1, 'tablet clock should be more legible at distance');
  assert.ok(html.indexOf('.solar-gauge canvas {\n      width: 76px;') > -1, 'solar gauges should shrink with the tighter top-row cards');
  assert.ok(html.indexOf('min-height: 84px;') > -1, 'solar top gauge cards should be shorter to free room for lower cards');
  assert.ok(html.indexOf('height: 92px;') > -1, 'solar top row should shrink further to avoid bottom-card truncation');
  assert.ok(html.indexOf('class="solar-gauge solar-gauge-generation skeleton"') > -1, 'generation gauge should use dedicated gauge class');
  assert.ok(html.indexOf('solar-gauge solar-gauge-usage') > -1, 'usage/import gauge should use dedicated gauge class');
  assert.ok(html.indexOf('.g-overlay {') > -1, 'gauge overlay text layer should exist');
  assert.ok(html.indexOf('id="generationGaugeText"') > -1, 'generation gauge overlay node missing');
  assert.ok(html.indexOf('id="usageGaugeText"') > -1, 'usage gauge overlay node missing');
  assert.ok(html.indexOf('.g-label {\n      position: absolute;\n      top: 6px;') > -1, 'gauge labels should sit at the top of the cards');
  assert.ok(html.indexOf('font-size: clamp(16px, 2.7vh, 22px);') > -1, 'gauge primary text should be scaled down to fit the smaller cards');
  assert.ok(html.indexOf('-webkit-text-stroke: 1.2px rgba(5, 8, 12, 0.98);') > -1, 'gauge primary text needs strong border contrast at the smaller size');
  assert.ok(html.indexOf('0 0 14px rgba(0, 0, 0, 0.7),') > -1, 'gauge text should include a stronger outer glow/halo');
  assert.ok(html.indexOf('font-size: clamp(10px, 1.7vh, 14px);') > -1, 'gauge secondary text should be scaled down to fit the smaller cards');
  assert.ok(html.indexOf('-webkit-text-stroke: 0.9px rgba(5, 8, 12, 0.95);') > -1, 'gauge secondary text needs a stronger border contrast');
  assert.strictEqual(html.indexOf('.g-value {'), -1, 'legacy side-value gauge text should be removed');
  assert.ok(html.indexOf('.solar-status-card {\n        min-height: 86px;') > -1, 'tablet solar status cards should be larger for readability');
  assert.ok(html.indexOf('.solar-status-value {\n        font-size: 40px;') > -1, 'tablet solar status values should be larger');
  assert.ok(html.indexOf('#binSummaryPage {') > -1, 'bins summary page style missing');
  assert.ok(html.indexOf('#binFocusPage {') > -1, 'bins focus page style missing');
  assert.ok(html.indexOf('.bin-row {') > -1, 'bin row style missing');
  assert.ok(html.indexOf('.bin-tag {') > -1, 'bin tag style missing');
  assert.ok(html.indexOf('#customCard {\n      display: flex;\n      flex-direction: column;\n      justify-content: center;\n      align-items: center;\n      text-align: center;') > -1, 'clock card should be center-aligned');
  assert.ok(html.indexOf('#weatherSummary {\n        font-size: clamp(20px, 3.3vh, 25px);') > -1, 'tablet weather summary should be larger');
  assert.ok(html.indexOf('.weather-temp-large {\n        font-size: clamp(34px, 5.4vh, 46px);') > -1, 'tablet weather temperature should be much larger');
  assert.ok(html.indexOf('function loadMapTileWithFallback(z, x, y) {') > -1, 'radar map tile fallback helper missing');
  assert.ok(html.indexOf('function loadMapTileFromLowerZoom(z, x, y) {') > -1, 'radar map tile fallback should support lower-zoom parent tiles');

  assert.ok(html.indexOf('id="solarChartsRow"') > -1, 'solar charts row container missing');
  assert.ok(html.indexOf('id="solarUsageChart"') > -1, 'primary solar usage chart canvas missing');
  assert.ok(html.indexOf('id="solarDawnChart"') > -1, 'solar dawn detail chart canvas missing');
  assert.ok(html.indexOf('id="solarFlowPanel"') > -1, 'solar flow summary panel missing');
  assert.ok(html.indexOf('id="solarFlowProduced"') > -1, 'solar flow produced metric missing');
  assert.ok(html.indexOf('id="solarFlowSelfUsed"') > -1, 'solar flow self-used metric missing');
  assert.ok(html.indexOf('id="solarFlowFeedIn"') > -1, 'solar flow feed-in metric missing');
  assert.ok(html.indexOf('id="solarFlowImport"') > -1, 'solar flow import metric missing');
  assert.ok(html.indexOf('id="solarFlowSelfPct"') > -1, 'solar flow self-consumption metric missing');
  assert.ok(html.indexOf('id="solarDataQualityBadge"') > -1, 'solar data-quality badge missing');
  assert.strictEqual(html.indexOf('id="solarBarChart"'), -1, 'legacy second solar chart should be removed');
  assert.ok(html.indexOf('min-height: 144px;') > -1, 'solar chart cards should be taller in main dashboard view');
  assert.ok(html.indexOf('height: 196px;') > -1, 'solar chart canvas should be taller in main dashboard view');
  assert.ok(html.indexOf('body.takeover-solar .chart-wrap {\n      height: 392px;') > -1, 'solar chart card should be doubled in takeover/fullscreen mode');
  assert.ok(html.indexOf('body.takeover-solar .chart {\n      height: 392px;') > -1, 'solar chart canvas should be doubled in takeover/fullscreen mode');
  assert.ok(html.indexOf('id="solarUsageLegend"') > -1, 'solar usage chart legend container missing');
  assert.strictEqual(html.indexOf('Usage (Self + Import)'), -1, 'primary solar chart label should be removed');
  assert.ok(html.indexOf('Generated') > -1, 'solar usage chart legend should include generated series');
  assert.ok(html.indexOf('Self-used') > -1, 'solar usage chart legend should include self-used series');
  assert.ok(html.indexOf('Import') > -1, 'solar usage chart legend should include import series');
  assert.ok(html.indexOf('id="solarStatusGrid"') > -1, 'solar status grid missing');
  assert.ok(html.indexOf('class="solar-status-card"') > -1, 'solar status cards missing');
  assert.ok(html.indexOf('class="solar-status-card solar-status-card-import"') > -1, 'grid import status card should use dedicated import card class');
  assert.strictEqual(html.indexOf('id="solarFooter"'), -1, 'legacy solar footer status line should be removed');
  assert.ok(html.indexOf('min-height: 70px;') > -1, 'solar daily cards should be shorter to create chart room');
  assert.ok(html.indexOf('.solar-status-label {\n      font-size: 12px;') > -1, 'solar status labels should be tightened to prevent clipping');
  assert.ok(html.indexOf('.solar-status-value {\n      font-family: var(--font-ui);\n      font-size: 26px;') > -1, 'solar status values should be reduced to prevent clipping');
  assert.ok(html.indexOf('padding: 7px 8px;') > -1, 'solar status cards should use tighter padding to avoid clipping');
  assert.ok(html.indexOf('id="weatherMainRow"') > -1, 'weather main row layout missing');
  assert.ok(html.indexOf('id="weatherRotator"') > -1, 'weather rotator container missing');
  assert.ok(html.indexOf('function buildCombinedStripCards(') > -1, 'combined strip card builder missing');
  assert.ok(html.indexOf('function renderCombinedStrip(') > -1, 'combined strip renderer missing');
  assert.ok(html.indexOf('function buildReminderStripCards(') > -1, 'reminder strip card builder missing');
  assert.ok(html.indexOf("date: item.dueDate || '',") > -1, 'reminder strip cards should carry the due date');
  assert.ok(html.indexOf("var combinedStripCards = buildCombinedStripCards(state);") > -1, 'state apply should build combined strip cards');
  assert.ok(html.indexOf('buildWeatherStripCards(state).concat(buildBinsStripCards(state), buildReminderStripCards(state));') > -1, 'combined strip should render weather first, then bins, then reminders');
  assert.ok(html.indexOf('#binCard {\n      display: none;') > -1, 'legacy bins panel should be hidden once combined into the strip');
  assert.ok(html.indexOf('strip-card-metrics') > -1, 'climate strip cards should render explicit metric rows');
  assert.strictEqual(html.indexOf('Temperature</span>'), -1, 'climate strip cards should remove verbose temperature labels');
  assert.strictEqual(html.indexOf('Humidity</span>'), -1, 'climate strip cards should remove verbose humidity labels');
  assert.ok(html.indexOf('strip-card-metric-label') > -1, 'climate strip cards should use compact icon-only metric labels');
  assert.ok(html.indexOf('.strip-card-metric-value.strip-card-metric-value-temp {\n      font-size: 30px;') > -1, 'home assistant temperature should use a larger 30px metric value');
  assert.ok(html.indexOf('.strip-battery-row {\n      grid-template-columns: auto 1fr auto;\n      font-size: 15px;') > -1, 'home assistant battery rows should use 15px text');
  assert.ok(html.indexOf('strip-card-value {\n      font-family: var(--font-display);\n      font-size: 28px;') > -1 && html.indexOf('white-space: nowrap;') > -1, 'strip values should stay on one line');
  assert.ok(html.indexOf('strip-internet-chart') > -1, 'internet strip cards should include a mini chart');
  assert.ok(html.indexOf("'<div class=\"strip-card-bg-icon is-hero\">' + card.iconMarkup + '</div>'") > -1, 'bin feature cards should render a centered background icon');
  assert.ok(html.indexOf('strip-card-bin-day') > -1, 'bin feature cards should render a dedicated day badge under the title');
  assert.ok(html.indexOf('.strip-card.strip-card-bin .strip-card-title {\n      grid-row: 3;\n      font-size: 30px;') > -1, 'bin feature title should be larger and prominent');
  assert.ok(html.indexOf('.strip-card.strip-card-bin .strip-card-head {\n      align-self: start;') > -1, 'bin feature kicker should stay pinned to the top');
  assert.ok(html.indexOf('.strip-card.strip-card-reminder {\n      width: 188px;\n      background: rgba(18, 20, 26, 0.86);\n      grid-template-rows: auto auto minmax(0, 1fr) auto;') > -1, 'reminder strip cards should reserve a footer row for the date');
  assert.ok(html.indexOf('.strip-card.strip-card-reminder .strip-card-title {\n      font-size: 27px;') > -1, 'reminder title should be larger on tablet');
  assert.ok(html.indexOf('.strip-card.strip-card-reminder .strip-card-copy {\n      font-size: 15px;') > -1, 'reminder note should be larger on tablet');
  assert.ok(html.indexOf('.strip-card-date {\n      font-size: 13px;') > -1, 'reminder cards should render a dedicated date row');
  assert.ok(html.indexOf("'<div class=\"strip-card-date\">' + escapeHtml(card.date || '') + '</div>' +") > -1, 'reminder cards should render their due date');
  assert.ok(html.indexOf('.strip-card.strip-card-forecast .strip-card-title {\n      margin-bottom: 8px;') > -1, 'forecast strip title should leave more space before rows');
  assert.ok(html.indexOf("'<article class=\"strip-card strip-card-weather strip-card-stack strip-card-weather-now\">' +") > -1, 'weather now renderer should use the dedicated centered layout variant');
  assert.ok(html.indexOf("'<div class=\"strip-card-head\"><div class=\"strip-card-kicker\">Weather Now</div><div class=\"strip-card-tag\">' + escapeHtml(card.icon || '☁') + '</div></div>' +\n            '<div class=\"strip-card-copy\">' + escapeHtml(card.summary || 'Unknown') + '</div>' +\n            '<div class=\"strip-card-value\">' + Number(card.tempC || 0).toFixed(1).replace(/\\\\.0$/, '') + '°C</div>' +") > -1, 'weather now cards should place the summary under the header and keep the temperature as the centered hero value');
  assert.ok(html.indexOf('.strip-weather-list {\n      display: grid;\n      gap: 3px;\n      align-content: start;') > -1, 'forecast list should tighten spacing so 15px rows do not clip');
  assert.ok(html.indexOf('.strip-weather-row {\n      font-size: 15px;\n      gap: 6px;\n      line-height: 1;') > -1, 'forecast rows should use 15px text with tighter spacing for tablet readability');
  assert.ok(html.indexOf('var WEATHER_ROTATE_MS = 15000;') > -1, 'weather rotator should use 15s interval');
  assert.ok(html.indexOf('function buildWeatherRotatorCards(') > -1, 'weather rotator card builder missing');
  assert.ok(html.indexOf('function weatherRotatorSignature(') > -1, 'weather rotator signature helper missing');
  assert.ok(html.indexOf('function renderWeatherRotatorCard(') > -1, 'weather rotator renderer missing');
  assert.ok(html.indexOf('function transitionWeatherRotatorTo(') > -1, 'weather rotator transition helper missing');
  assert.ok(html.indexOf("kind: 'forecast5'") > -1, 'weather rotator should include 5-day forecast card');
  assert.ok(html.indexOf('.weather-rotator-forecast-list') > -1, 'weather forecast card list style missing');
  assert.ok(html.indexOf('function iconForWeather(') > -1, 'weather forecast card should reuse weather icon mapping');
  assert.ok(html.indexOf('var lastWeatherRotatorSig = \'\';') > -1, 'weather rotator signature cache missing');
  assert.ok(html.indexOf('if (nextWeatherRotatorSig !== lastWeatherRotatorSig) {') > -1, 'weather rotator should restart only when card payload changes');
  assert.ok(html.indexOf('@keyframes weatherRotatorIn') > -1, 'weather rotator enter animation missing');
  assert.ok(html.indexOf('class=\\\"weather-rotator-card\\\"') > -1, 'weather rotator card frame missing');
  assert.ok(html.indexOf('grid-template-rows: auto minmax(0, 1fr) auto;') > -1, 'weather rotator cards should fill available height');
  assert.ok(html.indexOf('.weather-rotator-humidity-row') > -1, 'weather humidity row layout missing');
  assert.ok(html.indexOf('.weather-rotator-temp-row {\n      display: grid;\n      grid-template-columns: auto minmax(0, 1fr);\n      gap: 8px;\n      align-items: center;') > -1, 'weather temp icon/value should be midline aligned');
  assert.ok(html.indexOf('.weather-rotator-humidity-row {\n      display: grid;\n      grid-template-columns: auto minmax(0, 1fr);\n      gap: 8px;\n      align-items: center;') > -1, 'weather humidity icon/value should be midline aligned');
  assert.ok(html.indexOf('.weather-rotator-title {\n      font-family: var(--font-display);\n      font-size: 14px;') > -1, 'weather rotator title should be larger for tablet readability');
  assert.ok(html.indexOf('.weather-rotator-title-ha') > -1, 'ha weather title style missing');
  assert.ok(html.indexOf('font-size: 16px;') > -1, 'ha weather titles should be slightly larger');
  assert.ok(html.indexOf('.weather-rotator-divider') > -1, 'weather card divider style missing');
  assert.ok(html.indexOf('white-space: normal;') > -1, 'weather rotator title should wrap to avoid overlap');
  assert.ok(html.indexOf('.weather-rotator-humidity-value') > -1, 'weather humidity value style missing');
  assert.ok(html.indexOf('font-size: clamp(30px, 4.2vh, 40px);') > -1, 'weather humidity should be large enough for distance readability');
  assert.ok(html.indexOf('.weather-battery-row {\n      display: grid;\n      grid-template-columns: auto minmax(0, 1fr) auto;\n      gap: 8px;\n      align-items: center;\n      font-size: 18px;') > -1, 'battery card row text should be large enough for tablet readability');
  assert.ok(html.indexOf('id="weatherInternetMiniChart"') > -1, 'weather internet mini chart missing');
  assert.ok(html.indexOf('if (samples.length === 1) {') > -1, 'internet mini chart should render a visible point for a single sample');
  assert.ok(html.indexOf('weather-now-panel') > -1, 'weather current panel treatment missing');
  assert.ok(html.indexOf('class="weather-current weather-now-panel"') > -1, 'weather card should use featured current panel');
  assert.ok(html.indexOf('grid-template-columns: minmax(0, 0.95fr) minmax(0, 1.17fr);') > -1, 'weather row should prioritize forecast width');
  assert.ok(html.indexOf('font-size: clamp(13px, 2vh, 16px);') > -1, 'weather summary should remain readable while current temp grows');
  assert.ok(html.indexOf('font-size: clamp(38px, 5.7vh, 52px);') > -1, 'weather temperature should be larger for at-distance readability');
  assert.ok(html.indexOf('weather-temp-large') > -1, 'large weather temperature style missing');
  assert.ok(html.indexOf('#weatherStripPanel {') > -1 && html.indexOf('grid-template-rows: 1fr;') > -1, 'weather card should use full height without title row');
  assert.ok(html.indexOf('#weatherBinsStripViewport {\n      position: relative;\n      min-height: 0;\n      height: 100%;\n      overflow: hidden;') > -1, 'weather strip viewport should remain as a plain overflow container');
  assert.ok(html.indexOf('grid-template-rows: repeat(5, minmax(0, 1fr));') > -1, 'forecast should reserve space for five rows');
  assert.ok(html.indexOf('#weatherForecast {\n      margin-top: 8px;') > -1, 'forecast should sit lower below the Outlook header');
  assert.ok(html.indexOf('padding: 4px 8px;') > -1, 'forecast rows should be tighter to fit five days');
  assert.ok(html.indexOf('font-size: 19px;') > -1, 'forecast temperature should be larger for readability');
  assert.ok(html.indexOf('var forecast = Array.isArray(items) ? items.slice(0, 5) : [];') > -1, 'forecast renderer should show up to five days');
  assert.ok(html.indexOf('min-height: 0;') > -1, 'forecast layout should include truncation guards');
  assert.ok(html.indexOf('id="binSummaryPage"') > -1, 'bin summary page markup missing');
  assert.ok(html.indexOf('id="binRows"') > -1, 'bin rows container missing');
  assert.ok(html.indexOf('id="binFocusPage"') > -1, 'bin focus page markup missing');
  assert.ok(html.indexOf('id="binFocusLabel"') > -1, 'bin focus label missing');
  assert.ok(html.indexOf('id="binFocusTag"') > -1, 'bin focus tag missing');
  assert.strictEqual(html.indexOf('id="binFocusDetail"'), -1, 'bin focus detail row should be removed');
  assert.strictEqual(html.indexOf('id="binSummaryLabel"'), -1, 'bin summary headline should be removed to save space');
  assert.ok(html.indexOf('#binCard {\n      display: none;') > -1, 'legacy bins panel should be hidden once combined into the strip');
  assert.strictEqual(html.indexOf('id="binsType"'), -1, 'legacy single bins headline should be removed');
  assert.strictEqual(html.indexOf('id="binsDate"'), -1, 'legacy single bins subtitle should be removed');
  assert.ok(html.indexOf('function escapeHtml(') > -1, 'HTML escaping helper missing for bins rows');
  assert.ok(html.indexOf('function binsItemsSignature(') > -1, 'bins signature helper missing');
  assert.ok(html.indexOf('function renderBinsCard(') > -1, 'bins card render helper missing');
  assert.ok(html.indexOf('function binIconMarkup(') > -1, 'bins icon markup helper missing');
  assert.ok(html.indexOf('function buildBinsPages(') > -1, 'bins page builder missing');
  assert.ok(html.indexOf('function setBinCardPage(') > -1, 'bins page switch helper missing');
  assert.ok(html.indexOf('var BINS_PAGE_ROTATE_MS = 15000;') > -1, 'bins paging should match weather subcard cadence');
  assert.ok(html.indexOf('var summaryItems = items.slice(0, 3);') > -1, 'bins summary should cap visible rows to avoid truncation');
  assert.ok(html.indexOf('var focusItems = items.slice(0, 3);') > -1, 'bins focus cycle should follow the summary items');
  assert.ok(html.indexOf("if (nextBinsSig !== lastBinsSig) {\n          lastBinsSig = nextBinsSig;\n          renderBinsCard(state.bins || {});") > -1, 'bins card should only restart when content changes');
  assert.ok(html.indexOf("} else if (!binsPageTimer && Array.isArray((state.bins || {}).items) && (state.bins || {}).items.length > 1) {") > -1, 'bins timer should only restart when missing');
  assert.ok(html.indexOf("'<div class=\"bin-row-icon\">' + binIconMarkup(item, false) + '</div>'") > -1, 'bins renderer should use markup helper for icon rendering');
  assert.ok(html.indexOf('binRowsNode.innerHTML = rowsHtml;') > -1, 'bins renderer should populate summary rows');
  assert.ok(html.indexOf('#binFocusPage.is-yellow #binFocusIcon') > -1, 'focus recycle icon should use yellow tone');
  assert.ok(html.indexOf('#binFocusPage.is-green #binFocusIcon') > -1, 'focus organic icon should use green tone');
  assert.ok(html.indexOf('binFocusIconNode.innerHTML = binIconMarkup(focusItem, true);') > -1, 'focus bins icon should use markup helper for icon rendering');
  assert.ok(html.indexOf("binCardNode.classList.toggle('bin-card-focus',") > -1, 'bins card should toggle focus-page mode');
  assert.ok(html.indexOf("binCardNode.classList.toggle('bin-card-empty',") > -1, 'bins card should toggle empty mode');
  assert.ok(html.indexOf("if (binsPageTimer) {\n          clearInterval(binsPageTimer);") > -1, 'bins renderer should reset paging timer');
  assert.ok(html.indexOf("if (pages.length > 1) {\n          binsPageTimer = setInterval(function () {") > -1, 'bins paging should be conditional');
  assert.strictEqual(html.indexOf("document.getElementById('binsType')"), -1, 'legacy bins type lookup should be removed');
  assert.strictEqual(html.indexOf("document.getElementById('binsDate')"), -1, 'legacy bins date lookup should be removed');
  assert.ok(html.indexOf('id="radarGifImage"') > -1, 'radar gif layer missing');
  assert.ok(html.indexOf('id="radarEmbedFrame"') > -1, 'radar iframe layer missing');
  assert.ok(html.indexOf('radarEmbedFrame.src = radarIframeUrl;') > -1, 'radar iframe should use state-provided url');
  assert.ok(html.indexOf("var radarRenderMode = 'server_gif';") > -1, 'frontend radar mode should default to server_gif');
  assert.ok(html.indexOf("var radarIframeUrl = '';") > -1, 'frontend should track radar iframe url');
  assert.ok(html.indexOf('object-fit: cover;') > -1, 'radar gif should fill the viewport to remove side banding');
  assert.ok(html.indexOf('#radarGifImage {\n      position: absolute;') > -1 && html.indexOf('transform: none;') > -1, 'radar gif should not zoom so bottom timestamp stays visible');
  assert.ok(html.indexOf('function initRadarGifMode(') > -1, 'radar GIF init function should exist');
  assert.strictEqual(html.indexOf('var radarGifViewportSig = \'\';'), -1, 'radar gif should not use viewport signature cache');
  assert.ok(html.indexOf('var radarGifLastUpdatedAt = \'\';') > -1, 'radar gif realtime update marker missing');
  assert.ok(html.indexOf('var radarGifReloadQueued = false;') > -1, 'radar gif queued reload flag missing');
  assert.ok(html.indexOf('var radarGifReloadForceQueued = false;') > -1, 'radar gif queued force-reload flag missing');
  assert.ok(html.indexOf('function refreshRadarGifMode(') > -1, 'radar GIF viewport refresh helper missing');
  assert.ok(html.indexOf('refreshRadarGifMode(false);') > -1, 'resize path should refresh radar GIF dimensions');
  assert.ok(html.indexOf("fetch('/api/radar/animation')") > -1, 'radar gif mode refresh should use size-agnostic endpoint');
  assert.strictEqual(html.indexOf("fetch('/api/radar/animation?width=' + width + '&height=' + height)"), -1, 'radar gif mode refresh should not request viewport dimensions');
  assert.ok(html.indexOf("patch.radar && patch.radar.gifUpdatedAt") > -1, 'realtime state should inspect radar gif update timestamp');
  assert.ok(html.indexOf('if (gifUpdatedAt && gifUpdatedAt !== radarGifLastUpdatedAt) {') > -1, 'gif reload should only trigger on update timestamp changes');
  assert.ok(html.indexOf('radarGifReloadQueued = true;') > -1, 'gif update should queue reload when image is already loading');
  assert.ok(html.indexOf('if (radarGifReloadQueued) {') > -1, 'gif onload/onerror should flush queued reload');
  assert.ok(html.indexOf('function loadRadarGif(force) {') > -1, 'gif loader should support forced reloads');
  assert.strictEqual(html.indexOf('setRadarMode(payload.mode);'), -1, 'frontend should map server mode explicitly');
  assert.strictEqual(html.indexOf("src += (src.indexOf('?') > -1 ? '&' : '?') + 'strict=1';"), -1, 'gif loader should not force strict rendering reloads');
  assert.ok(html.indexOf('if (radarGifLoading) {') > -1, 'gif loader should guard against concurrent in-flight requests');
  assert.ok(html.indexOf('radarGifReloadForceQueued = radarGifReloadForceQueued || !!force;') > -1, 'queued reload should preserve force intent');
  assert.ok(html.indexOf('var queuedForce = radarGifReloadForceQueued;') > -1, 'gif onload/onerror should drain queued force mode');
  assert.ok(html.indexOf('loadRadarGif(false);') > -1, 'realtime gif updates should request latest gif without strict blocking');
  assert.ok(html.indexOf('function loadRadarGif(') > -1, 'radar GIF load function should exist');
  assert.ok(html.indexOf('function maybeStartRadarLoop(') > -1, 'radar startup loop gate missing');
  assert.ok(html.indexOf('requestAnimationFrame(animateRadar);') > -1, 'radar startup should launch canvas animation loop immediately');
  assert.ok(html.indexOf('id="radarGifStatus"') > -1, 'radar GIF status indicator missing');
  assert.ok(html.indexOf('function updateRadarGifStatus(') > -1, 'radar GIF status updater missing');
  assert.ok(html.indexOf("if (radarRenderMode === 'rainviewer_iframe') {") > -1, 'frontend should support iframe radar mode');
  assert.strictEqual(html.indexOf('await drawLayer(tiles, 1, function (tx, ty) { return loadMapTileWithFallback(z, tx, ty); }, MAP_TILE_OVERDRAW);'), -1, 'frontend should not draw map png tiles for radar');
  assert.ok(html.indexOf('Radar animation generating...') > -1, 'gif mode should render loading message without png tile fetches');
  assert.ok(html.indexOf('radarGifImage.onload') > -1, 'gif readiness promotion missing');
  assert.ok(html.indexOf('function classifyRadarRain(') > -1, 'radar rain classification helper missing');
  assert.ok(html.indexOf('var isYellow = (r > 150 && g > 130 && b < 160);') > -1, 'radar classifier should detect yellow precipitation echoes');
  assert.ok(html.indexOf('Heavy rain nearby') > -1, 'heavy rain indicator message missing');
  assert.ok(html.indexOf('importReady') > -1, 'solar import readiness gating missing');
  assert.ok(html.indexOf('function isSolarBackendPending(') > -1, 'solar backend pending helper missing');
  assert.ok(html.indexOf('isSolarBackendPending(state.fronius || {})') > -1, 'solar loading should depend on backend readiness while data is zero');
  assert.ok(html.indexOf("document.getElementById('solarStatusImport').textContent = importReady") > -1, 'solar import display should use readiness');
  assert.ok(html.indexOf('function sumSolarBinsKwh(') > -1, 'solar daily bins helper missing');
  assert.ok(html.indexOf('today.importReady && Number(today.importKwh || 0) > 0') > -1, 'solar data detection should ignore unready import estimates');
  assert.ok(html.indexOf('today.generatedReady && Number(today.generatedKwh || 0) > 0') > -1, 'solar data detection should respect generated readiness');
  assert.ok(html.indexOf('function hasAnySolarBinEnergy(') > -1, 'solar bins energy helper missing');
  assert.ok(html.indexOf('var todayHasTotals = Number(todayRaw.generatedKwh || 0) > 0 || Number(todayRaw.importKwh || 0) > 0 || Number(todayRaw.exportKwh || 0) > 0;') > -1, 'solar chart loading should consider non-zero totals while bins are empty');
  assert.ok(html.indexOf('var chartsLoading = !binsHaveEnergy && (isSolarBackendPending(state.fronius || {}) || todayHasTotals);') > -1, 'solar charts should stay in loading mode until bins are populated');
  assert.ok(html.indexOf('function drawHourAxis(') > -1, 'solar chart hour axis helper missing');
  assert.ok(html.indexOf('function drawPowerAxis(') > -1, 'solar chart power axis helper missing');
  assert.ok(html.indexOf('for (var level = 2000; level <= topLevel; level += 2000)') > -1, 'solar chart should draw horizontal guides every 2kW');
  assert.ok(html.indexOf("ctx.fillText(String(Math.round(level / 1000)) + 'kW', pad - 2, y);") > -1, 'solar chart should label horizontal guides in kW');
  assert.ok(html.indexOf('for (var hour = 0; hour <= 21; hour += 3)') > -1, 'solar chart should label hours every 3');
  assert.ok(html.indexOf('var slot = (hour / 24) * count;') > -1, 'solar hour ticks should map against rendered bar count');
  assert.ok(html.indexOf('drawPowerAxis(ctx, w, h, pad, chartBottom, generatedLineMaxY);') > -1, 'solar usage chart should draw the Y-axis power guides');
  assert.ok(html.indexOf('drawHourAxis(ctx, w, h, pad, chartBottom, barsCount, barW);') > -1, 'solar hour axis should align to fixed bar geometry');
  assert.ok(html.indexOf("ctx.font = '14px ' + CANVAS_FONT_FAMILY;") > -1, 'solar chart hour labels should be larger for tablet readability');
  assert.ok(html.indexOf('function drawLoadingBars(') > -1, 'solar loading chart helper missing');
  assert.ok(html.indexOf("ctx.fillStyle = '#5fe08b';") > -1, 'solar feed-in bars should use green highlight');
  assert.ok(html.indexOf('rgba(126, 225, 160') > -1, 'solar loading bars should use green tone');
  assert.ok(html.indexOf('setSolarChartsLoading(chartsLoading);') > -1, 'solar loading chart toggling missing');
  assert.ok(html.indexOf('function drawUsageHourlyBars(') > -1, 'usage hourly draw helper missing');
  assert.ok(html.indexOf('var pad = 28;') > -1, 'solar usage chart should reserve a left gutter for Y-axis labels');
  assert.ok(html.indexOf('var barsCount = data.length;') > -1, 'solar usage chart should adapt bar count to the source resolution');
  assert.ok(html.indexOf('var bucketHours = barsCount > 0 ? (24 / barsCount) : 1;') > -1, 'solar usage chart should infer bucket duration from the source resolution');
  assert.ok(html.indexOf('var generatedWh = Math.max(0, Number(bin.generatedWh || 0)) / bucketHours;') > -1, 'solar generation should be converted from bucket energy back to average power');
  assert.ok(html.indexOf('var b = Math.max(0, Number(bin.importWh || 0)) / bucketHours;') > -1, 'import series should be converted from bucket energy back to average power');
  assert.ok(html.indexOf("ctx.fillStyle = 'rgba(112, 168, 255, 0.44)';") > -1, 'import bars should use a cooler translucent blue fill');
  assert.strictEqual(html.indexOf('function buildGeneratedHistorySeries('), -1, 'generated history filtering should move to the server so browser timezone cannot collapse the chart');
  assert.strictEqual(html.indexOf('function dayKeyForTimestampInZone('), -1, 'browser timezone day-key helper should be removed from the chart path');
  assert.strictEqual(html.indexOf('function secondOfDayForTimestampInZone('), -1, 'browser timezone second-of-day helper should be removed from the chart path');
  assert.ok(html.indexOf('function drawGeneratedLine(') > -1, 'generated line helper missing for hybrid chart');
  assert.strictEqual(html.indexOf('function smoothSeries('), -1, 'generated line should avoid averaging helper');
  assert.ok(html.indexOf("ctx.fillStyle = 'rgba(255, 226, 122, 0.42)';") > -1, 'generated series should render as a translucent yellow fill');
  assert.ok(html.indexOf('if (Number(point.value || 0) <= 0) {\n            if (drawing) {\n              ctx.lineTo(lastX, chartBottom);') > -1, 'generated fill should close each positive segment before zero-value gaps');
  assert.ok(html.indexOf("ctx.lineJoin = 'round';") > -1, 'generated hybrid line should use rounded joins');
  assert.ok(html.indexOf("ctx.lineCap = 'round';") > -1, 'generated hybrid line should use rounded caps');
  assert.strictEqual(html.indexOf('ctx.quadraticCurveTo('), -1, 'generated hybrid line should avoid curve interpolation');
  assert.ok(html.indexOf('var usagePeakWh = 1;') > -1, 'usage bars should track usage peak independently');
  assert.ok(html.indexOf('usagePeakWh = Math.max(usagePeakWh, Math.max((Number(item.selfWh || 0) + Number(item.importWh || 0)) / bucketHours, Number(item.generatedWh || 0) / bucketHours));') > -1, 'usage bars should scale from average power, not raw bucket energy');
  assert.ok(html.indexOf('var selfWh = generatedWh > 0 ? Math.min(generatedWh, Math.max(0, Number(bin.selfWh || 0)) / bucketHours) : 0;') > -1, 'self-used bars should drop to zero when there is no generation');
  assert.ok(html.indexOf('if (bh > 0) {\n            ctx.fillStyle = \'rgba(112, 168, 255, 0.44)\';') > -1, 'import bars should not draw a baseline pixel when zero');
  assert.ok(html.indexOf('if (ah > 0) {\n            ctx.fillStyle = \'#8edb7c\';') > -1, 'self-used bars should not draw a baseline pixel when zero');
  assert.ok(html.indexOf('var generatedSeries = Array.isArray(solarGeneratedSeries) ? solarGeneratedSeries.slice() : [];') > -1, 'generated series should come from server-prepared history data');
  assert.ok(html.indexOf('var generatedLinePeakWh = generatedSeries.reduce(function (peak, point) { return Math.max(peak, Number((point && point.value) || 0)); }, 0);') > -1, 'generated line scale should derive peak from raw values');
  assert.ok(html.indexOf('var generatedCapWh = Number(pricingConfig.inverterCapacityKw || 6.3) * 1000;') > -1, 'generated line scaling should use inverter capacity with a 6.3kW default');
  assert.ok(html.indexOf('usagePeakWh = Math.max(usagePeakWh, Math.max((Number(item.selfWh || 0) + Number(item.importWh || 0)) / bucketHours, Number(item.generatedWh || 0) / bucketHours));') > -1, 'usage chart scale should consider generated output as well as usage stack');
  assert.ok(html.indexOf('var generatedLineMaxY = Math.max(usagePeakWh, generatedCapWh, generatedLinePeakWh);') > -1, 'generated line should expand the chart max if archive power exceeds the configured ceiling');
  assert.ok(html.indexOf('.solar-gauge-usage.is-no-import') > -1, 'usage/import gauge should expose no-import state class');
  assert.ok(html.indexOf('.solar-gauge-usage.is-importing') > -1, 'usage/import gauge should expose importing state class');
  assert.ok(html.indexOf('.solar-gauge-generation.is-inactive') > -1, 'generation gauge should expose inactive solar state class');
  assert.ok(html.indexOf('.solar-gauge-generation.is-maxed') > -1, 'generation gauge should expose maxed pulse state class');
  assert.ok(html.indexOf('.solar-gauge-generation.is-maxed {\n      background: rgb(25 68 35 / 92%);') > -1, 'generation gauge should turn green when near inverter max');
  assert.ok(html.indexOf('#generationGaugeText,\n    #generationGaugeText .g-overlay-main,\n    #generationGaugeText .g-overlay-sub {\n      color: #00ff3d') > -1, 'generation gauge text should always be green');
  assert.ok(html.indexOf('#generationGaugeText.is-inactive') > -1, 'generation gauge text should expose inactive solar state class');
  assert.ok(html.indexOf('#usageGaugeText.is-no-import') > -1, 'usage gauge text should expose no-import state class');
  assert.ok(html.indexOf('#usageGaugeText.is-importing') > -1, 'usage gauge text should expose importing state class');
  assert.ok(html.indexOf("generationGaugeSubNode.textContent = genW <= 0.02 ? 'No solar activity' : 'now';") > -1, 'generation gauge should note no solar activity when generation is zero');
  assert.ok(html.indexOf("generationGaugeNode.classList.toggle('is-inactive', genW <= 0.02);") > -1, 'generation gauge should switch to inactive state when solar generation is zero');
  assert.ok(html.indexOf("usageGaugeNode.classList.toggle('is-importing', importW > 0.02);") > -1, 'usage gauge should switch to import state when importing');
  assert.ok(html.indexOf("usageGaugeTextNode.classList.toggle('is-importing', importW > 0.02);") > -1, 'usage gauge text should switch to import state when importing');
  assert.ok(html.indexOf("generationGaugeNode.classList.toggle('is-maxed', genW >= capW * 0.98);") > -1, 'generation gauge should pulse when near inverter max');
  assert.ok(html.indexOf("var capW = Math.max(1000, Number(pricingConfig.inverterCapacityKw || 6.3) * 1000);") > -1, 'generation gauge should default to a 6.3kW inverter ceiling');
  assert.ok(html.indexOf("solarStatusImportCard.classList.toggle('is-importing', importReady && Number(today.importKwh || 0) > 0);") > -1, 'grid import status card should switch to import accent when import is positive');
  assert.ok(html.indexOf('.solar-status-card-import.is-importing {\n      background: rgba(120, 24, 24, 0.18);') > -1, 'grid import status card should use the red inactive-solar accent when importing');
  assert.ok(html.indexOf("style=\"background:#70a8ff;\"") > -1, 'solar usage legend should show blue import swatch');
  assert.ok(html.indexOf("ctx.fillStyle = 'rgba(112, 168, 255, 0.44)';") > -1, 'import bars should be more transparent and cooler');
  assert.ok(html.indexOf("ctx.fillStyle = 'rgba(255, 226, 122, 0.42)';") > -1, 'generated area should use a brighter gold tone');
  assert.ok(html.indexOf('function drawDawnQuarterBars(') > -1, 'dawn quarter draw helper missing');
  assert.ok(html.indexOf('function buildSolarPanelSignatures(') > -1, 'solar panel signature helper missing');
  assert.ok(html.indexOf('var usageChartBins = Array.isArray(state.solarDailyBins) && state.solarDailyBins.length ? state.solarDailyBins : (Array.isArray(state.solarUsageHourly) ? state.solarUsageHourly : []);') > -1, 'usage chart should prefer half-hour solar bins to avoid a visual lag');
  assert.ok(html.indexOf('var solarGeneratedSeries = Array.isArray(state.solarGeneratedHistory) ? state.solarGeneratedHistory : [];') > -1, 'usage chart should read server-prepared generated history');
  assert.ok(html.indexOf('var panelSigs = buildSolarPanelSignatures(usageChartBins, solarGeneratedSeries, dawnQuarterBins, flowSummary, chartsLoading);') > -1, 'solar panel signatures should include the generated history source');
  assert.ok(html.indexOf('drawUsageHourlyBars(usageBarCtx, usageBarCanvas, usageChartBins, solarGeneratedSeries);') > -1, 'usage chart should render from the selected bins plus generated history');
  assert.ok(html.indexOf('if (panelSigs.usage !== lastSolarUsageSig) {') > -1, 'usage panel redraw guard missing');
  assert.ok(html.indexOf('if (panelSigs.dawn !== lastSolarDawnSig) {') > -1, 'dawn panel redraw guard missing');
  assert.ok(html.indexOf('if (panelSigs.flow !== lastSolarFlowSig) {') > -1, 'flow panel redraw guard missing');
  assert.ok(html.indexOf("solarDataQuality === 'realtime_estimated'") > -1, 'estimated data-quality branch missing');
  assert.strictEqual(html.indexOf('function reduceBinsForChart('), -1, 'legacy chart reduction helper should be removed');
  assert.ok(html.indexOf('var stateFetchInFlight = false;') > -1, 'state fetch overlap guard missing');
  assert.ok(html.indexOf('if (stateFetchInFlight) { return; }') > -1, 'state fetch throttle branch missing');
  assert.ok(html.indexOf('var radarLoopStarted = false;') > -1, 'deferred radar startup flag missing');
  assert.ok(html.indexOf('if (radarLoopStarted || !firstDataApplied) {') > -1, 'deferred radar startup guard missing');
  assert.ok(html.indexOf('requestAnimationFrame(animateRadar);\n        initRadarGifMode();') === -1, 'startup should not kick off png tile animation loop');
  assert.ok(html.indexOf("} else if (payload && payload.mode === 'bom_static') {") > -1, 'radar mode mapper should include bom_static mode');
  assert.ok(html.indexOf('if (payload && payload.mode === \'bom_static\' && payload.bomImagePath) {') > -1, 'radar init should use bomImagePath in bom_static mode');
  assert.ok(html.indexOf('} else if (payload && payload.gifPath) {') > -1, 'radar init should keep gifPath path for gif mode');
  assert.ok(html.indexOf("if (radarRenderMode === 'server_gif') {\n              radarGifUrl = String(state.radar.gifPath);") > -1, 'state apply should only bind gifPath while in server_gif mode');
  assert.ok(html.indexOf("if (radarRenderMode === 'bom_static') {\n              radarGifUrl = String(state.radar.bomImagePath);") > -1, 'state apply should only bind bomImagePath while in bom_static mode');
  assert.ok(html.indexOf("if (radarRenderMode === 'server_gif') {\n                radarGifUrl = String(patch.radar.gifPath);") > -1, 'realtime patch should only bind gifPath while in server_gif mode');
  assert.ok(html.indexOf("if (radarRenderMode === 'bom_static') {\n                radarGifUrl = String(patch.radar.bomImagePath);") > -1, 'realtime patch should only bind bomImagePath while in bom_static mode');
  assert.ok(html.indexOf('window.location.replace(buildViewUrl(viewMode, untilMs, nextAtMs));') > -1, 'fullscreen switch should force a page reload');
  assert.ok(html.indexOf("document.body.classList.add('blackout');") > -1, 'fullscreen switch should enable blackout overlay');
  assert.ok(html.indexOf('setTimeout(function () {\n          reloadToView(viewMode, untilMs, nextAtMs);\n        }, TAKEOVER_BLACKOUT_MS);') > -1, 'fullscreen transition should delay reload to show blackout');
  assert.ok(html.indexOf('transitionReloadToView(mode === \'radar\' ? \'radar\' : \'solar\', now + durationMs, nextAtMs);') > -1, 'takeover start should use blackout transition');
  assert.ok(html.indexOf('transitionReloadToView(\'main\', 0, nextAtMs);') > -1, 'takeover end should use blackout transition');
  assert.ok(html.indexOf("var lastFocusMode = '';") > -1, 'focus rotation should persist last mode across reloads');
  assert.ok(html.indexOf("lastFocusMode = normalizeFocusMode(search.get('lastfocus'));") > -1, 'initial view parsing should restore last focus mode from URL');
  assert.ok(html.indexOf("url.searchParams.set('lastfocus', lastFocusMode);") > -1, 'view reload URL should carry last focus mode');
  assert.ok(html.indexOf("var lastIdx = views.indexOf(lastFocusMode);") > -1, 'next takeover picker should reference last focus mode');
  assert.ok(html.indexOf('return views[(lastIdx + 1) % views.length];') > -1, 'next takeover picker should advance past previous focus mode');
  assert.ok(html.indexOf('lastFocusMode = mode;') > -1, 'begin takeover should update last focus mode before reload');
  assert.ok(html.indexOf('function applyTimeOfDayTheme(') > -1, 'time-of-day color helper missing');
  assert.ok(html.indexOf("document.body.classList.remove('time-night', 'time-twilight', 'time-day');") > -1, 'time-of-day class reset missing');
  assert.ok(html.indexOf('body.time-night #timeBig') > -1, 'night time color style missing');
  assert.ok(html.indexOf('body.time-twilight #timeBig') > -1, 'twilight time color style missing');
  assert.ok(html.indexOf('body.time-day #timeBig') > -1, 'day time color style missing');
  assert.ok(html.indexOf('function formatDateShort(') > -1, 'short date formatter missing');
  assert.ok(html.indexOf('ctx.imageSmoothingEnabled = false;') > -1, 'radar smoothing guard missing');
  assert.ok(html.indexOf('var radarClassifyCanvas = document.createElement(\'canvas\');') > -1, 'radar-only classification canvas missing');
  assert.ok(html.indexOf('if (!classified.hasSignal) {') > -1, 'radar low-signal fallback guard missing');
  assert.ok(html.indexOf('drawX: Math.round(') > -1, 'integer snapped tile draw coordinates missing');
};
